### ISSUE TITLE
Errors in python microservices of the demo app after provisioning completes

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#372]
The issue is here and it's related to OpenTelemetry exporter:
/usr/local/lib/python3.7/site-packages/google/auth/_default.py:354

```python
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
at default (/usr/local/lib/python3.7/site-packages/google/auth/_default.py:354)
at _create_composite_credentials (/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py:217)
at create_channel (/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py:280)
at create_channel (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py:99)
at __init__ (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py:69)
at __init__ (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py:187)
at __init__ (/usr/local/lib/python3.7/site-packages/opentelemetry/exporter/cloud_trace/__init__.py:90)
at <module> (email_server.py:218)
```

**Comment by gzhao408** [comment]
Should this be an issue opened in the opentelemetry repo maybe?

**Comment by gzhao408** [comment]
I'm having trouble reproducing this issue, where did you get this error log from?

What we can do is error first if we can't find the `GOOGLE_APPLICATION_CREDENTIALS ` or `GCLOUD_PROJECT` or `PROJECT_ID` or `GOOGLE_CLOUD_PROJECT` environment variables, but it's more likely to create misleading error messages that aren't actually related to authentication (like the case with the golang services).

**Comment by eaberman** [comment]
I may be getting this error as well. I looked in Error Reporting in the Sandbox I provisioned in non-Google account yesterday. This is what it looks like.

![Screenshot 2020-08-25 at 4 04 05 PM](https://user-images.githubusercontent.com/38052620/91227797-ba455e00-e6ec-11ea-88ae-d5517d5357c5.png)
![Screenshot 2020-08-25 at 4 05 33 PM](https://user-images.githubusercontent.com/38052620/91227841-d5b06900-e6ec-11ea-86e7-726473b1aafa.png)

**Comment by gzhao408** [comment]
Yep I see it now too. @eaberman do the python traces show up for you?

**Comment by eaberman** [comment]
I see:
```
Traceback (most recent call last):
  File "/recommendationservice/recommendation_server.py", line 82, in <module>
    cloud_trace_exporter = CloudTraceSpanExporter()
  File "/usr/local/lib/python3.7/site-packages/opentelemetry/exporter/cloud_trace/__init__.py", line 90, in __init__
    self.client = client or TraceServiceClient()
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 187, in __init__
    address=api_endpoint, channel=channel, credentials=credentials,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py", line 69, in __init__
    "grpc.max_receive_message_length": -1,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py", line 101, in create_channel
    address, credentials=credentials, scopes=cls._OAUTH_SCOPES, **kwargs
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 280, in create_channel
    quota_project_id=quota_project_id,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 217, in _create_composite_credentials
    credentials, _ = google.auth.default(scopes=scopes)
  File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 354, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```
Is that what you meant?

**Comment by simonz130** [comment]
There are two things we can do:

1) Set the environment variables according to what the Exporters want. (PROJECT_ID, GOOGLE_PROJECT_ID or whatever that is). We should do it in a single place in code of python microservices so it's easy to change/remove later on
2) Open bugs on upstream repository where the exporter is developed. There should be a single way to define auth for the library.

Alternatively, we can see if the exporter provides means for custom authentication where we can authenticate and then provide the credential object to the exporter.

**Comment by nicoleczhu** [comment]
I made a [PR here](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/435) which fixed the error by passing Google credentials as a secret to GKE. But it fails our CI tests since they are locally run and we don't provision google credentials.

My original thoughts on solutions were:
- Post injecting envars into pods solve the CI issue. But then we still get error logs in the few seconds right after deploying pods, right before the envars are injected.
- Use Helm to manage deployment/env conditions, so local deployments/CI don't see the envar declarations.
- Wait until upstream bug is fixed, since this PR just patches behavior that shouldn't be occurring in the first place
- Hope GKE logging and monitoring agents will use Workload Identity rather than the node's service account soon, as mentioned in Limitations here.

Thought I'd ask here as well in case there's a really simple solution I'm not seeing... Thanks!

**Comment by nicoleczhu** [comment]
> There are two things we can do:
> 
> 1. Set the environment variables according to what the Exporters want. (PROJECT_ID, GOOGLE_PROJECT_ID or whatever that is). We should do it in a single place in code of python microservices so it's easy to change/remove later on
> 2. Open bugs on upstream repository where the exporter is developed. There should be a single way to define auth for the library.
> 
> Alternatively, we can see if the exporter provides means for custom authentication where we can authenticate and then provide the credential object to the exporter.

Related issue filed here which mentions this: https://github.com/googleapis/google-auth-library-python/issues/604
