### ISSUE TITLE
Flaky e2e monitoring integration tests

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/cloud-ops-sandbox#564]
Some of our e2e tests are failing at the monitoring test step. Doing a re-run seems to help, but we should look into the root issue

```
2020-11-11T23:17:48.6759661Z ##[group]Run set -x
2020-11-11T23:17:48.6760333Z [36;1mset -x[0m
2020-11-11T23:17:48.6760878Z [36;1m# install dependencies[0m
2020-11-11T23:17:48.6761749Z [36;1mpython3 -m pip install -r tests/requirements.txt[0m
2020-11-11T23:17:48.6762585Z [36;1m# authenticate cluster[0m
2020-11-11T23:17:48.6764081Z [36;1mCLUSTER_ZONE=$(gcloud container clusters list --filter="name:cloud-ops-sandbox" --project stackdriver-sandbox-e2e --format="value(zone)")[0m
2020-11-11T23:17:48.6766086Z [36;1mgcloud container clusters get-credentials cloud-ops-sandbox --zone "$CLUSTER_ZONE"[0m
2020-11-11T23:17:48.6767110Z [36;1m# run tests[0m
2020-11-11T23:17:48.6768121Z [36;1mpython3 tests/monitoring_integration_test.py stackdriver-sandbox-e2e[0m
2020-11-11T23:17:48.6796743Z shell: /bin/bash -e {0}
2020-11-11T23:17:48.6797195Z env:
2020-11-11T23:17:48.6797970Z   PROJECT_ID: stackdriver-sandbox-e2e
2020-11-11T23:17:48.6798720Z ##[endgroup]
2020-11-11T23:17:48.6886012Z + python3 -m pip install -r tests/requirements.txt
2020-11-11T23:17:50.7727879Z Defaulting to user installation because normal site-packages is not writeable
2020-11-11T23:17:50.8566844Z Requirement already satisfied: google-cloud-monitoring>=1.0.0 in /home/sanche/.local/lib/python3.5/site-packages (from -r tests/requirements.txt (line 1)) (1.0.0)
2020-11-11T23:17:50.8636554Z Requirement already satisfied: google-cloud-monitoring-dashboards>=1.0.0 in /home/sanche/.local/lib/python3.5/site-packages (from -r tests/requirements.txt (line 2)) (1.0.0)
2020-11-11T23:17:50.8701897Z Requirement already satisfied: tabulate>=0.8.7 in /home/sanche/.local/lib/python3.5/site-packages (from -r tests/requirements.txt (line 3)) (0.8.7)
2020-11-11T23:17:50.9328632Z Requirement already satisfied: google-api-python-client>=1.10.0 in /home/sanche/.local/lib/python3.5/site-packages (from -r tests/requirements.txt (line 4)) (1.10.0)
2020-11-11T23:17:50.9497189Z Requirement already satisfied: oauth2client>=4.1.3 in /home/sanche/.local/lib/python3.5/site-packages (from -r tests/requirements.txt (line 5)) (4.1.3)
2020-11-11T23:17:50.9674836Z Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.14.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (1.22.1)
2020-11-11T23:17:50.9840454Z Requirement already satisfied: google-auth>=1.16.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (1.20.1)
2020-11-11T23:17:51.0082891Z Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (3.0.1)
2020-11-11T23:17:51.0201282Z Requirement already satisfied: google-auth-httplib2>=0.0.3 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (0.0.4)
2020-11-11T23:17:51.0498832Z Requirement already satisfied: httplib2<1dev,>=0.9.2 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (0.18.1)
2020-11-11T23:17:51.0520095Z Requirement already satisfied: six<2dev,>=1.6.1 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (1.15.0)
2020-11-11T23:17:51.0680202Z Requirement already satisfied: rsa>=3.1.4 in /home/sanche/.local/lib/python3.5/site-packages (from oauth2client>=4.1.3->-r tests/requirements.txt (line 5)) (4.6)
2020-11-11T23:17:51.0799726Z Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/sanche/.local/lib/python3.5/site-packages (from oauth2client>=4.1.3->-r tests/requirements.txt (line 5)) (0.2.8)
2020-11-11T23:17:51.0932124Z Requirement already satisfied: pyasn1>=0.1.7 in /home/sanche/.local/lib/python3.5/site-packages (from oauth2client>=4.1.3->-r tests/requirements.txt (line 5)) (0.4.8)
2020-11-11T23:17:51.1129335Z Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (2.24.0)
2020-11-11T23:17:51.1380119Z Requirement already satisfied: setuptools>=34.0.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (49.6.0)
2020-11-11T23:17:51.1832899Z Requirement already satisfied: protobuf>=3.12.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (3.13.0)
2020-11-11T23:17:51.1983639Z Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (1.52.0)
2020-11-11T23:17:51.2163803Z Requirement already satisfied: pytz in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (2020.1)
2020-11-11T23:17:51.2815471Z Requirement already satisfied: grpcio<2.0dev,>=1.29.0; extra == "grpc" in /home/sanche/.local/lib/python3.5/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (1.31.0)
2020-11-11T23:17:51.2953262Z Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/sanche/.local/lib/python3.5/site-packages (from google-auth>=1.16.0->google-api-python-client>=1.10.0->-r tests/requirements.txt (line 4)) (4.1.1)
2020-11-11T23:17:51.3172654Z Requirement already satisfied: certifi>=2017.4.17 in /home/sanche/.local/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (2020.6.20)
2020-11-11T23:17:51.3193795Z Requirement already satisfied: chardet<4,>=3.0.2 in /home/sanche/.local/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (3.0.4)
2020-11-11T23:17:51.3397206Z Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/sanche/.local/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (1.25.10)
2020-11-11T23:17:51.3593559Z Requirement already satisfied: idna<3,>=2.5 in /home/sanche/.local/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-monitoring>=1.0.0->-r tests/requirements.txt (line 1)) (2.10)
2020-11-11T23:17:51.5251863Z WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
2020-11-11T23:17:51.5254765Z You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2020-11-11T23:17:51.5851570Z ++ gcloud container clusters list --filter=name:cloud-ops-sandbox --project stackdriver-sandbox-e2e '--format=value(zone)'
2020-11-11T23:17:51.8857344Z WARNING: Could not setup log file in /home/sanche/.config/gcloud/logs, (IOError: [Errno 13] Permission denied: u'/home/sanche/.config/gcloud/logs/2020.11.11/23.17.51.879115.log')
2020-11-11T23:17:52.3614833Z + CLUSTER_ZONE=us-central1-b
2020-11-11T23:17:52.3616225Z + gcloud container clusters get-credentials cloud-ops-sandbox --zone us-central1-b
2020-11-11T23:17:52.6687198Z WARNING: Could not setup log file in /home/sanche/.config/gcloud/logs, (IOError: [Errno 13] Permission denied: u'/home/sanche/.config/gcloud/logs/2020.11.11/23.17.52.661904.log')
2020-11-11T23:17:52.7762136Z Fetching cluster endpoint and auth data.
2020-11-11T23:17:52.8483244Z kubeconfig entry generated for cloud-ops-sandbox.
2020-11-11T23:17:52.8951286Z + python3 tests/monitoring_integration_test.py stackdriver-sandbox-e2e
2020-11-11T23:17:55.4112998Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52168), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.4115785Z   'Channel deallocated!')
2020-11-11T23:17:55.4894225Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52176), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.4895318Z   'Channel deallocated!')
2020-11-11T23:17:55.5598486Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52184), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.5602721Z   'Channel deallocated!')
2020-11-11T23:17:55.6489908Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52192), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.6491256Z   'Channel deallocated!')
2020-11-11T23:17:55.7348195Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52200), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.7353574Z   'Channel deallocated!')
2020-11-11T23:17:55.9074097Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52208), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.9077103Z   'Channel deallocated!')
2020-11-11T23:17:55.9078382Z /home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52216), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:55.9079477Z   'Channel deallocated!')
2020-11-11T23:17:56.0576042Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52224), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.0579575Z   'Channel deallocated!')
2020-11-11T23:17:56.2222166Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52232), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.2223427Z   'Channel deallocated!')
2020-11-11T23:17:56.4101304Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52240), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.4104919Z   'Channel deallocated!')
2020-11-11T23:17:56.5816244Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52248), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.5819264Z   'Channel deallocated!')
2020-11-11T23:17:56.7974500Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52256), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.7977508Z   'Channel deallocated!')
2020-11-11T23:17:56.9642483Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52264), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:56.9645048Z   'Channel deallocated!')
2020-11-11T23:17:57.1202874Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52272), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:57.1208354Z   'Channel deallocated!')
2020-11-11T23:17:57.2625741Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52280), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:57.2626893Z   'Channel deallocated!')
2020-11-11T23:17:57.4395721Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52288), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:57.4396936Z   'Channel deallocated!')
2020-11-11T23:17:57.6411256Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52296), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:57.6415119Z   'Channel deallocated!')
2020-11-11T23:17:57.8259861Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52304), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:57.8264838Z   'Channel deallocated!')
2020-11-11T23:17:58.1169854Z ../home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52312), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.1174778Z   'Channel deallocated!')
2020-11-11T23:17:58.2654219Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52320), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.2657573Z   'Channel deallocated!')
2020-11-11T23:17:58.3986731Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52328), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.3991393Z   'Channel deallocated!')
2020-11-11T23:17:58.5532980Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52336), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.5536149Z   'Channel deallocated!')
2020-11-11T23:17:58.6799440Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52344), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.6802446Z   'Channel deallocated!')
2020-11-11T23:17:58.8091991Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52352), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.8094003Z   'Channel deallocated!')
2020-11-11T23:17:58.9438632Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52360), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:58.9440588Z   'Channel deallocated!')
2020-11-11T23:17:59.0827959Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52368), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.0833211Z   'Channel deallocated!')
2020-11-11T23:17:59.2062751Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52376), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.2065498Z   'Channel deallocated!')
2020-11-11T23:17:59.2609418Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52384), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.2610526Z   'Channel deallocated!')
2020-11-11T23:17:59.4829915Z FF./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52408), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.4833002Z   'Channel deallocated!')
2020-11-11T23:17:59.6605837Z F./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=20, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52424), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.6607083Z   'Channel deallocated!')
2020-11-11T23:17:59.7410925Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=20, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52432), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.7414825Z   'Channel deallocated!')
2020-11-11T23:17:59.7947329Z ./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=20, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52440), raddr=('169.254.169.254', 80)>
2020-11-11T23:17:59.7950626Z   'Channel deallocated!')
2020-11-11T23:18:02.2096105Z FF./home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52464), raddr=('169.254.169.254', 80)>
2020-11-11T23:18:02.2100153Z   'Channel deallocated!')
2020-11-11T23:18:02.2486378Z F/home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52494), raddr=('169.254.169.254', 80)>
2020-11-11T23:18:02.2490150Z   'Channel deallocated!')
2020-11-11T23:18:02.2491815Z /home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52502), raddr=('169.254.169.254', 80)>
2020-11-11T23:18:02.2493063Z   'Channel deallocated!')
2020-11-11T23:18:02.4192723Z .F/home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52510), raddr=('169.254.169.254', 80)>
2020-11-11T23:18:02.4196880Z   'Channel deallocated!')
2020-11-11T23:18:02.4208711Z F/home/sanche/.local/lib/python3.5/site-packages/grpc/_channel.py:1128: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.128.15.198', 52518), raddr=('169.254.169.254', 80)>
2020-11-11T23:18:02.4211476Z   'Channel deallocated!')
2020-11-11T23:18:02.4212273Z 
2020-11-11T23:18:02.4213005Z ======================================================================
2020-11-11T23:18:02.4214562Z FAIL: testAdServiceSloAlertExists (__main__.TestSloAlertPolicy)
2020-11-11T23:18:02.4216470Z Test that the Alerting Policies for the Frontend Service SLO get created.
2020-11-11T23:18:02.4218048Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4218983Z Traceback (most recent call last):
2020-11-11T23:18:02.4222271Z   File "tests/monitoring_integration_test.py", line 415, in testAdServiceSloAlertExists
2020-11-11T23:18:02.4224174Z     self.assertTrue(found_availability_alert)
2020-11-11T23:18:02.4225432Z AssertionError: False is not true
2020-11-11T23:18:02.4226136Z 
2020-11-11T23:18:02.4226723Z ======================================================================
2020-11-11T23:18:02.4228112Z FAIL: testCartServiceSloAlertExists (__main__.TestSloAlertPolicy)
2020-11-11T23:18:02.4230877Z Test that the Alerting Policies for the Cart Service SLO get created.
2020-11-11T23:18:02.4232455Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4233262Z Traceback (most recent call last):
2020-11-11T23:18:02.4234936Z   File "tests/monitoring_integration_test.py", line 387, in testCartServiceSloAlertExists
2020-11-11T23:18:02.4236638Z     self.assertTrue(found_availability_alert)
2020-11-11T23:18:02.4237731Z AssertionError: False is not true
2020-11-11T23:18:02.4238430Z 
2020-11-11T23:18:02.4239038Z ======================================================================
2020-11-11T23:18:02.4240507Z FAIL: testCurrencyServiceSloAlertExists (__main__.TestSloAlertPolicy)
2020-11-11T23:18:02.4242414Z Test that the Alerting Policies for the Currency Service SLO get created.
2020-11-11T23:18:02.4243919Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4245419Z Traceback (most recent call last):
2020-11-11T23:18:02.4247429Z   File "tests/monitoring_integration_test.py", line 401, in testCurrencyServiceSloAlertExists
2020-11-11T23:18:02.4249272Z     self.assertTrue(found_availability_alert)
2020-11-11T23:18:02.4250362Z AssertionError: False is not true
2020-11-11T23:18:02.4251579Z 
2020-11-11T23:18:02.4252732Z ======================================================================
2020-11-11T23:18:02.4260288Z FAIL: testProductCatalogServiceSloAlertExists (__main__.TestSloAlertPolicy)
2020-11-11T23:18:02.4262494Z Test that the Alerting Policies for the Product Catalog Service SLO get created.
2020-11-11T23:18:02.4263975Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4264656Z Traceback (most recent call last):
2020-11-11T23:18:02.4266397Z   File "tests/monitoring_integration_test.py", line 394, in testProductCatalogServiceSloAlertExists
2020-11-11T23:18:02.4268301Z     self.assertTrue(found_availability_alert)
2020-11-11T23:18:02.4269474Z AssertionError: False is not true
2020-11-11T23:18:02.4269970Z 
2020-11-11T23:18:02.4270404Z ======================================================================
2020-11-11T23:18:02.4271969Z FAIL: testRecommendationServiceSloAlertExists (__main__.TestSloAlertPolicy)
2020-11-11T23:18:02.4274014Z Test that the Alerting Policies for the Recommendation Service SLO get created.
2020-11-11T23:18:02.4275443Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4276011Z Traceback (most recent call last):
2020-11-11T23:18:02.4277757Z   File "tests/monitoring_integration_test.py", line 408, in testRecommendationServiceSloAlertExists
2020-11-11T23:18:02.4281868Z     self.assertTrue(found_availability_alert)
2020-11-11T23:18:02.4282831Z AssertionError: False is not true
2020-11-11T23:18:02.4283352Z 
2020-11-11T23:18:02.4283751Z ======================================================================
2020-11-11T23:18:02.4284829Z FAIL: testNumberOfUptimeChecks (__main__.TestUptimeCheck)
2020-11-11T23:18:02.4286073Z " Test that ensures there is only one uptime check created
2020-11-11T23:18:02.4289252Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4289788Z Traceback (most recent call last):
2020-11-11T23:18:02.4290812Z   File "tests/monitoring_integration_test.py", line 96, in testNumberOfUptimeChecks
2020-11-11T23:18:02.4291946Z     self.assertEqual(len(config_list), 1)
2020-11-11T23:18:02.4292625Z AssertionError: 2 != 1
2020-11-11T23:18:02.4292993Z 
2020-11-11T23:18:02.4293329Z ======================================================================
2020-11-11T23:18:02.4295442Z FAIL: testUptimeCheckAlertingPolicyNotificationChannel (__main__.TestUptimeCheck)
2020-11-11T23:18:02.4298060Z Test that our single notification channel was created.
2020-11-11T23:18:02.4299163Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4299633Z Traceback (most recent call last):
2020-11-11T23:18:02.4301281Z   File "tests/monitoring_integration_test.py", line 129, in testUptimeCheckAlertingPolicyNotificationChannel
2020-11-11T23:18:02.4303102Z     self.assertEqual(len(channel_list), 1)
2020-11-11T23:18:02.4303798Z AssertionError: 2 != 1
2020-11-11T23:18:02.4304184Z 
2020-11-11T23:18:02.4304627Z ======================================================================
2020-11-11T23:18:02.4305387Z FAIL: testUptimeCheckName (__main__.TestUptimeCheck)
2020-11-11T23:18:02.4306487Z Verifies the configured IP address of the uptime check matches the external IP
2020-11-11T23:18:02.4307739Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4308244Z Traceback (most recent call last):
2020-11-11T23:18:02.4309357Z   File "tests/monitoring_integration_test.py", line 108, in testUptimeCheckName
2020-11-11T23:18:02.4310631Z     self.assertEqual(config.monitored_resource.labels["host"], self.external_ip)
2020-11-11T23:18:02.4311996Z AssertionError: '34.67.239.90' != '35.202.36.16'
2020-11-11T23:18:02.4312628Z - 34.67.239.90
2020-11-11T23:18:02.4312905Z + 35.202.36.16
2020-11-11T23:18:02.4313150Z 
2020-11-11T23:18:02.4313373Z 
2020-11-11T23:18:02.4313929Z ----------------------------------------------------------------------
2020-11-11T23:18:02.4314297Z Ran 42 tests in 7.209s
2020-11-11T23:18:02.4315089Z 
```

**Comment by Daniel-Sanche** [comment]
This doesn't seem to be relevant any more
